### ISSUE TITLE
player_traderMenu Error

### ISSUE THREAD

**Issue by Markokil321** [vbawol/DayZ-Epoch#1616] opened 2015-02-02 20:34 UTC
Error in expression < 0;
if (_index < 0) exitWith {};
while {count TraderItemList < 1} do {sleep 1};
>
  Error position: <count TraderItemList < 1} do {sleep 1};
>
  Error count: Type Number, expected Array,Config entry
File mpmissions\__CUR_MP.Chernarus\Mods\Trader\SingleCurrency\player_traderMenu.sqf, line 130

screw this github code: http://i.imgur.com/dWUJ3RO.png

**Comment by ebaydayz** [comment] 2015-02-02 23:04
I've noticed the same error often. To reproduce just open a trader menu, click on a category, then click on a specific item. 

```
Error in expression < 0;
if (_index < 0) exitWith {};
while {count TraderItemList < 1} do { sleep 1; >
  Error position: <count TraderItemList < 1} do { sleep 1; >
  Error count: Type Number, expected Array,Config entry
File z\addons\dayz_code\compile\player_traderMenuHive.sqf, line 174
```

It is because the TraderItemList variable is initialized as a number ( -1 ) when it should be an array ( [] ). Not sure how @maca134 overlooked that when he made this. Anyway, tested and fixed here:
https://github.com/vbawol/DayZ-Epoch/pull/1617

**Comment by rayjensen** [comment] 2015-02-03 04:11
Same goes for TraderCatList

**Comment by ebaydayz** [comment] 2015-02-04 19:14
Yup, thanks for pointing that out @rayjensen. Submitted the fixes as a pull request.

**Comment by ebaydayz** [comment] 2015-02-04 19:30
Also just noticed this was brought up in an earlier issue:
https://github.com/vbawol/DayZ-Epoch/issues/1367

The trader menu has other problems like this one:
https://github.com/vbawol/DayZ-Epoch/issues/1296

In general spam clicking different categories and then items really fast can cause different errors with the Hive version because of the way it is written (sleep 1 while loading). For example:
```
Error in expression <PLAIN DOWN"];
};
_item = TraderItemList select _index;
_data = [_item select 0, >
  Error position: <select _index;
_data = [_item select 0, >
  Error Zero divisor
File z\addons\dayz_code\compile\player_traderMenuHive.sqf, line 198
```
It is attempting to select an index from the array that does not exist. Probably from spam clicking different categories with higher numbers of items before TraderItemList can update. That is a minor problem though that would probably take a full menu redesign to fix.

**Comment by Windmolders** [comment] 2015-07-01 22:15
@ebaydayz We could just check if the selecteIndex is a number before proceding with the next code to fix this 'issue'

**Comment by ebaydayz** [comment] 2015-07-02 20:57
@Windmolders The original error Markokil321 reported in this issue has already been fixed by these commits:
https://github.com/vbawol/DayZ-Epoch/pull/1618
https://github.com/vbawol/DayZ-Epoch/pull/1619
https://github.com/vbawol/DayZ-Epoch/pull/1620

I've tested that with the rest of the current 1.0.6 code and can confirm the error is fixed. This can be closed now.

The other error I mentioned above is a separate problem with the Hive version of the menu only. It is unrelated and much less common.

**Closed** 2015-07-02 21:39 UTC
